name = "react-router-app-tet"
compatibility_date = "2024-11-06"
main = "./build/server/index.js"

assets = { directory = "./build/client" }

[vars]
VALUE_FROM_CLOUDFLARE = "Hello from Cloudflare"

[[workflows]]
name = "workflows-starter"
binding = "MY_WORKFLOW"
class_name = "MyWorkflow"
